version: "2"
plugins:
  shellcheck:
    enabled: true
  #https://github.com/codeclimate-community/codeclimate-govet/issues/25
  govet:
    enabled: false
  gofmt:
    enabled: true
  golint:
    enabled: true
checks:
  return-statements:
    enabled: false
exclude_patterns:
  - "testdata/"
  - "**/vendor/"
  - "**/*_test.go"
  - "config/"
  - '**/spec/'
  - '**/test/'
  - '**/tests/'
  - '**/zz_generated.deepcopy.go'
